CLASS zbp_r_pru_cmr_header DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zr_pru_cmr_header .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zbp_r_pru_cmr_header IMPLEMENTATION.
ENDCLASS.
