CLASS LHC_ZR_PRU_MESSAGE DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ZrPruMessage
        RESULT result,
      PerformVisualRecognition FOR MODIFY
            IMPORTING keys FOR ACTION ZrPruMessage~PerformVisualRecognition.
ENDCLASS.

CLASS LHC_ZR_PRU_MESSAGE IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
  METHOD PerformVisualRecognition.
  ENDMETHOD.

ENDCLASS.
